/* Static snapshot of liquid US-listed names: S&P 500 constituents plus widely
   covered mid-caps and high-profile listings, spread across all 11 GICS sectors.

   Names are hardcoded so the bulk load does not have to spend an API call per
   ticker just to learn a company name — that halves the cold-load cost. The
   company profile (logo, industry, market cap) is fetched lazily when a row is
   opened instead.

   This is a point-in-time list. Tickers get acquired, renamed and delisted; any
   entry Finnhub no longer recognises returns no data and is silently dropped
   from the board, so staleness here degrades quietly rather than breaking. */

const UNIVERSE = [
  // ── Information Technology ────────────────────────────────────────
  ['AAPL', 'Apple', 'Information Technology'],
  ['MSFT', 'Microsoft', 'Information Technology'],
  ['NVDA', 'NVIDIA', 'Information Technology'],
  ['AVGO', 'Broadcom', 'Information Technology'],
  ['ORCL', 'Oracle', 'Information Technology'],
  ['CRM', 'Salesforce', 'Information Technology'],
  ['AMD', 'Advanced Micro Devices', 'Information Technology'],
  ['ADBE', 'Adobe', 'Information Technology'],
  ['ACN', 'Accenture', 'Information Technology'],
  ['CSCO', 'Cisco Systems', 'Information Technology'],
  ['INTC', 'Intel', 'Information Technology'],
  ['TXN', 'Texas Instruments', 'Information Technology'],
  ['QCOM', 'Qualcomm', 'Information Technology'],
  ['IBM', 'IBM', 'Information Technology'],
  ['NOW', 'ServiceNow', 'Information Technology'],
  ['INTU', 'Intuit', 'Information Technology'],
  ['AMAT', 'Applied Materials', 'Information Technology'],
  ['MU', 'Micron Technology', 'Information Technology'],
  ['LRCX', 'Lam Research', 'Information Technology'],
  ['ADI', 'Analog Devices', 'Information Technology'],
  ['KLAC', 'KLA Corporation', 'Information Technology'],
  ['PANW', 'Palo Alto Networks', 'Information Technology'],
  ['SNPS', 'Synopsys', 'Information Technology'],
  ['CDNS', 'Cadence Design Systems', 'Information Technology'],
  ['CRWD', 'CrowdStrike', 'Information Technology'],
  ['ANET', 'Arista Networks', 'Information Technology'],
  ['MSI', 'Motorola Solutions', 'Information Technology'],
  ['ROP', 'Roper Technologies', 'Information Technology'],
  ['ADSK', 'Autodesk', 'Information Technology'],
  ['FTNT', 'Fortinet', 'Information Technology'],
  ['NXPI', 'NXP Semiconductors', 'Information Technology'],
  ['MCHP', 'Microchip Technology', 'Information Technology'],
  ['TEL', 'TE Connectivity', 'Information Technology'],
  ['APH', 'Amphenol', 'Information Technology'],
  ['GLW', 'Corning', 'Information Technology'],
  ['HPQ', 'HP Inc.', 'Information Technology'],
  ['DELL', 'Dell Technologies', 'Information Technology'],
  ['HPE', 'Hewlett Packard Enterprise', 'Information Technology'],
  ['STX', 'Seagate Technology', 'Information Technology'],
  ['WDC', 'Western Digital', 'Information Technology'],
  ['NTAP', 'NetApp', 'Information Technology'],
  ['KEYS', 'Keysight Technologies', 'Information Technology'],
  ['TER', 'Teradyne', 'Information Technology'],
  ['ON', 'ON Semiconductor', 'Information Technology'],
  ['SWKS', 'Skyworks Solutions', 'Information Technology'],
  ['QRVO', 'Qorvo', 'Information Technology'],
  ['MPWR', 'Monolithic Power Systems', 'Information Technology'],
  ['ENPH', 'Enphase Energy', 'Information Technology'],
  ['FSLR', 'First Solar', 'Information Technology'],
  ['TDY', 'Teledyne Technologies', 'Information Technology'],
  ['ZBRA', 'Zebra Technologies', 'Information Technology'],
  ['TRMB', 'Trimble', 'Information Technology'],
  ['PTC', 'PTC Inc.', 'Information Technology'],
  ['TYL', 'Tyler Technologies', 'Information Technology'],
  ['GDDY', 'GoDaddy', 'Information Technology'],
  ['AKAM', 'Akamai Technologies', 'Information Technology'],
  ['FFIV', 'F5 Inc.', 'Information Technology'],
  ['EPAM', 'EPAM Systems', 'Information Technology'],
  ['CTSH', 'Cognizant Technology', 'Information Technology'],
  ['IT', 'Gartner', 'Information Technology'],
  ['CDW', 'CDW Corporation', 'Information Technology'],
  ['JBL', 'Jabil', 'Information Technology'],
  ['FLEX', 'Flex Ltd.', 'Information Technology'],
  ['SMCI', 'Super Micro Computer', 'Information Technology'],
  ['VRSN', 'VeriSign', 'Information Technology'],
  ['GEN', 'Gen Digital', 'Information Technology'],
  ['ARM', 'Arm Holdings', 'Information Technology'],
  ['APP', 'AppLovin', 'Information Technology'],
  ['DDOG', 'Datadog', 'Information Technology'],
  ['SNOW', 'Snowflake', 'Information Technology'],
  ['NET', 'Cloudflare', 'Information Technology'],
  ['ZS', 'Zscaler', 'Information Technology'],
  ['MDB', 'MongoDB', 'Information Technology'],
  ['TEAM', 'Atlassian', 'Information Technology'],
  ['HUBS', 'HubSpot', 'Information Technology'],
  ['WDAY', 'Workday', 'Information Technology'],
  ['VEEV', 'Veeva Systems', 'Information Technology'],
  ['ZM', 'Zoom Communications', 'Information Technology'],
  ['DOCU', 'Docusign', 'Information Technology'],
  ['OKTA', 'Okta', 'Information Technology'],
  ['TWLO', 'Twilio', 'Information Technology'],
  ['PLTR', 'Palantir Technologies', 'Information Technology'],
  ['SHOP', 'Shopify', 'Information Technology'],
  ['U', 'Unity Software', 'Information Technology'],
  ['ESTC', 'Elastic', 'Information Technology'],
  ['CFLT', 'Confluent', 'Information Technology'],
  ['GTLB', 'GitLab', 'Information Technology'],
  ['S', 'SentinelOne', 'Information Technology'],
  ['PATH', 'UiPath', 'Information Technology'],
  ['ASAN', 'Asana', 'Information Technology'],
  ['BOX', 'Box Inc.', 'Information Technology'],
  ['DBX', 'Dropbox', 'Information Technology'],
  ['WIX', 'Wix.com', 'Information Technology'],
  ['NTNX', 'Nutanix', 'Information Technology'],
  ['PSTG', 'Pure Storage', 'Information Technology'],
  ['CIEN', 'Ciena', 'Information Technology'],
  ['LSCC', 'Lattice Semiconductor', 'Information Technology'],
  ['RMBS', 'Rambus', 'Information Technology'],
  ['ALTR', 'Altair Engineering', 'Information Technology'],
  ['MANH', 'Manhattan Associates', 'Information Technology'],

  // ── Communication Services ────────────────────────────────────────
  ['GOOGL', 'Alphabet Class A', 'Communication Services'],
  ['GOOG', 'Alphabet Class C', 'Communication Services'],
  ['META', 'Meta Platforms', 'Communication Services'],
  ['NFLX', 'Netflix', 'Communication Services'],
  ['DIS', 'Walt Disney', 'Communication Services'],
  ['CMCSA', 'Comcast', 'Communication Services'],
  ['T', 'AT&T', 'Communication Services'],
  ['VZ', 'Verizon Communications', 'Communication Services'],
  ['TMUS', 'T-Mobile US', 'Communication Services'],
  ['CHTR', 'Charter Communications', 'Communication Services'],
  ['WBD', 'Warner Bros. Discovery', 'Communication Services'],
  ['EA', 'Electronic Arts', 'Communication Services'],
  ['TTWO', 'Take-Two Interactive', 'Communication Services'],
  ['RBLX', 'Roblox', 'Communication Services'],
  ['MTCH', 'Match Group', 'Communication Services'],
  ['PINS', 'Pinterest', 'Communication Services'],
  ['SNAP', 'Snap Inc.', 'Communication Services'],
  ['SPOT', 'Spotify Technology', 'Communication Services'],
  ['LYV', 'Live Nation Entertainment', 'Communication Services'],
  ['OMC', 'Omnicom Group', 'Communication Services'],
  ['IPG', 'Interpublic Group', 'Communication Services'],
  ['NWSA', 'News Corp Class A', 'Communication Services'],
  ['FOXA', 'Fox Corporation', 'Communication Services'],
  ['ROKU', 'Roku', 'Communication Services'],
  ['TTD', 'The Trade Desk', 'Communication Services'],
  ['Z', 'Zillow Group', 'Communication Services'],
  ['YELP', 'Yelp', 'Communication Services'],
  ['NYT', 'New York Times', 'Communication Services'],

  // ── Consumer Discretionary ────────────────────────────────────────
  ['AMZN', 'Amazon.com', 'Consumer Discretionary'],
  ['TSLA', 'Tesla', 'Consumer Discretionary'],
  ['HD', 'Home Depot', 'Consumer Discretionary'],
  ['MCD', "McDonald's", 'Consumer Discretionary'],
  ['LOW', "Lowe's Companies", 'Consumer Discretionary'],
  ['BKNG', 'Booking Holdings', 'Consumer Discretionary'],
  ['TJX', 'TJX Companies', 'Consumer Discretionary'],
  ['SBUX', 'Starbucks', 'Consumer Discretionary'],
  ['NKE', 'Nike', 'Consumer Discretionary'],
  ['ABNB', 'Airbnb', 'Consumer Discretionary'],
  ['CMG', 'Chipotle Mexican Grill', 'Consumer Discretionary'],
  ['ORLY', "O'Reilly Automotive", 'Consumer Discretionary'],
  ['AZO', 'AutoZone', 'Consumer Discretionary'],
  ['MAR', 'Marriott International', 'Consumer Discretionary'],
  ['HLT', 'Hilton Worldwide', 'Consumer Discretionary'],
  ['GM', 'General Motors', 'Consumer Discretionary'],
  ['F', 'Ford Motor', 'Consumer Discretionary'],
  ['RIVN', 'Rivian Automotive', 'Consumer Discretionary'],
  ['LCID', 'Lucid Group', 'Consumer Discretionary'],
  ['LVS', 'Las Vegas Sands', 'Consumer Discretionary'],
  ['MGM', 'MGM Resorts', 'Consumer Discretionary'],
  ['WYNN', 'Wynn Resorts', 'Consumer Discretionary'],
  ['CZR', 'Caesars Entertainment', 'Consumer Discretionary'],
  ['RCL', 'Royal Caribbean', 'Consumer Discretionary'],
  ['CCL', 'Carnival', 'Consumer Discretionary'],
  ['NCLH', 'Norwegian Cruise Line', 'Consumer Discretionary'],
  ['DRI', 'Darden Restaurants', 'Consumer Discretionary'],
  ['YUM', 'Yum! Brands', 'Consumer Discretionary'],
  ['QSR', 'Restaurant Brands Intl.', 'Consumer Discretionary'],
  ['DPZ', "Domino's Pizza", 'Consumer Discretionary'],
  ['WING', 'Wingstop', 'Consumer Discretionary'],
  ['LULU', 'Lululemon Athletica', 'Consumer Discretionary'],
  ['ROST', 'Ross Stores', 'Consumer Discretionary'],
  ['BURL', 'Burlington Stores', 'Consumer Discretionary'],
  ['DKS', "Dick's Sporting Goods", 'Consumer Discretionary'],
  ['BBY', 'Best Buy', 'Consumer Discretionary'],
  ['ULTA', 'Ulta Beauty', 'Consumer Discretionary'],
  ['TSCO', 'Tractor Supply', 'Consumer Discretionary'],
  ['GRMN', 'Garmin', 'Consumer Discretionary'],
  ['WHR', 'Whirlpool', 'Consumer Discretionary'],
  ['LEN', 'Lennar', 'Consumer Discretionary'],
  ['DHI', 'D.R. Horton', 'Consumer Discretionary'],
  ['PHM', 'PulteGroup', 'Consumer Discretionary'],
  ['NVR', 'NVR Inc.', 'Consumer Discretionary'],
  ['TOL', 'Toll Brothers', 'Consumer Discretionary'],
  ['POOL', 'Pool Corporation', 'Consumer Discretionary'],
  ['LKQ', 'LKQ Corporation', 'Consumer Discretionary'],
  ['GPC', 'Genuine Parts', 'Consumer Discretionary'],
  ['APTV', 'Aptiv', 'Consumer Discretionary'],
  ['BWA', 'BorgWarner', 'Consumer Discretionary'],
  ['LEA', 'Lear Corporation', 'Consumer Discretionary'],
  ['HAS', 'Hasbro', 'Consumer Discretionary'],
  ['MAT', 'Mattel', 'Consumer Discretionary'],
  ['EBAY', 'eBay', 'Consumer Discretionary'],
  ['ETSY', 'Etsy', 'Consumer Discretionary'],
  ['CHWY', 'Chewy', 'Consumer Discretionary'],
  ['W', 'Wayfair', 'Consumer Discretionary'],
  ['CVNA', 'Carvana', 'Consumer Discretionary'],
  ['DASH', 'DoorDash', 'Consumer Discretionary'],
  ['LYFT', 'Lyft', 'Consumer Discretionary'],
  ['EXPE', 'Expedia Group', 'Consumer Discretionary'],
  ['VFC', 'VF Corporation', 'Consumer Discretionary'],
  ['RL', 'Ralph Lauren', 'Consumer Discretionary'],
  ['PVH', 'PVH Corp.', 'Consumer Discretionary'],
  ['TPR', 'Tapestry', 'Consumer Discretionary'],
  ['CPRI', 'Capri Holdings', 'Consumer Discretionary'],
  ['DECK', 'Deckers Outdoor', 'Consumer Discretionary'],
  ['CROX', 'Crocs', 'Consumer Discretionary'],
  ['SKX', 'Skechers', 'Consumer Discretionary'],
  ['KMX', 'CarMax', 'Consumer Discretionary'],
  ['AAP', 'Advance Auto Parts', 'Consumer Discretionary'],

  // ── Consumer Staples ──────────────────────────────────────────────
  ['PG', 'Procter & Gamble', 'Consumer Staples'],
  ['KO', 'Coca-Cola', 'Consumer Staples'],
  ['PEP', 'PepsiCo', 'Consumer Staples'],
  ['COST', 'Costco Wholesale', 'Consumer Staples'],
  ['WMT', 'Walmart', 'Consumer Staples'],
  ['PM', 'Philip Morris Intl.', 'Consumer Staples'],
  ['MO', 'Altria Group', 'Consumer Staples'],
  ['MDLZ', 'Mondelez International', 'Consumer Staples'],
  ['CL', 'Colgate-Palmolive', 'Consumer Staples'],
  ['KMB', 'Kimberly-Clark', 'Consumer Staples'],
  ['GIS', 'General Mills', 'Consumer Staples'],
  ['K', 'Kellanova', 'Consumer Staples'],
  ['HSY', 'Hershey', 'Consumer Staples'],
  ['STZ', 'Constellation Brands', 'Consumer Staples'],
  ['KDP', 'Keurig Dr Pepper', 'Consumer Staples'],
  ['MNST', 'Monster Beverage', 'Consumer Staples'],
  ['KHC', 'Kraft Heinz', 'Consumer Staples'],
  ['SYY', 'Sysco', 'Consumer Staples'],
  ['KR', 'Kroger', 'Consumer Staples'],
  ['ADM', 'Archer-Daniels-Midland', 'Consumer Staples'],
  ['TSN', 'Tyson Foods', 'Consumer Staples'],
  ['HRL', 'Hormel Foods', 'Consumer Staples'],
  ['CAG', 'Conagra Brands', 'Consumer Staples'],
  ['CPB', "Campbell's Company", 'Consumer Staples'],
  ['SJM', 'J.M. Smucker', 'Consumer Staples'],
  ['MKC', 'McCormick', 'Consumer Staples'],
  ['CHD', 'Church & Dwight', 'Consumer Staples'],
  ['CLX', 'Clorox', 'Consumer Staples'],
  ['EL', 'Estée Lauder', 'Consumer Staples'],
  ['DG', 'Dollar General', 'Consumer Staples'],
  ['DLTR', 'Dollar Tree', 'Consumer Staples'],
  ['TAP', 'Molson Coors', 'Consumer Staples'],
  ['LW', 'Lamb Weston', 'Consumer Staples'],
  ['CASY', "Casey's General Stores", 'Consumer Staples'],
  ['BJ', "BJ's Wholesale Club", 'Consumer Staples'],
  ['COKE', 'Coca-Cola Consolidated', 'Consumer Staples'],

  // ── Health Care ───────────────────────────────────────────────────
  ['LLY', 'Eli Lilly', 'Health Care'],
  ['UNH', 'UnitedHealth Group', 'Health Care'],
  ['JNJ', 'Johnson & Johnson', 'Health Care'],
  ['ABBV', 'AbbVie', 'Health Care'],
  ['MRK', 'Merck & Co.', 'Health Care'],
  ['TMO', 'Thermo Fisher Scientific', 'Health Care'],
  ['ABT', 'Abbott Laboratories', 'Health Care'],
  ['DHR', 'Danaher', 'Health Care'],
  ['PFE', 'Pfizer', 'Health Care'],
  ['AMGN', 'Amgen', 'Health Care'],
  ['BMY', 'Bristol-Myers Squibb', 'Health Care'],
  ['ISRG', 'Intuitive Surgical', 'Health Care'],
  ['BSX', 'Boston Scientific', 'Health Care'],
  ['VRTX', 'Vertex Pharmaceuticals', 'Health Care'],
  ['GILD', 'Gilead Sciences', 'Health Care'],
  ['MDT', 'Medtronic', 'Health Care'],
  ['SYK', 'Stryker', 'Health Care'],
  ['CI', 'Cigna Group', 'Health Care'],
  ['ELV', 'Elevance Health', 'Health Care'],
  ['CVS', 'CVS Health', 'Health Care'],
  ['REGN', 'Regeneron Pharmaceuticals', 'Health Care'],
  ['ZTS', 'Zoetis', 'Health Care'],
  ['BDX', 'Becton Dickinson', 'Health Care'],
  ['HCA', 'HCA Healthcare', 'Health Care'],
  ['MCK', 'McKesson', 'Health Care'],
  ['COR', 'Cencora', 'Health Care'],
  ['CAH', 'Cardinal Health', 'Health Care'],
  ['EW', 'Edwards Lifesciences', 'Health Care'],
  ['A', 'Agilent Technologies', 'Health Care'],
  ['IDXX', 'IDEXX Laboratories', 'Health Care'],
  ['IQV', 'IQVIA Holdings', 'Health Care'],
  ['RMD', 'ResMed', 'Health Care'],
  ['DXCM', 'DexCom', 'Health Care'],
  ['MTD', 'Mettler-Toledo', 'Health Care'],
  ['WST', 'West Pharmaceutical', 'Health Care'],
  ['BIIB', 'Biogen', 'Health Care'],
  ['MRNA', 'Moderna', 'Health Care'],
  ['ILMN', 'Illumina', 'Health Care'],
  ['BAX', 'Baxter International', 'Health Care'],
  ['ZBH', 'Zimmer Biomet', 'Health Care'],
  ['HOLX', 'Hologic', 'Health Care'],
  ['STE', 'Steris', 'Health Care'],
  ['ALGN', 'Align Technology', 'Health Care'],
  ['PODD', 'Insulet', 'Health Care'],
  ['VTRS', 'Viatris', 'Health Care'],
  ['CNC', 'Centene', 'Health Care'],
  ['MOH', 'Molina Healthcare', 'Health Care'],
  ['UHS', 'Universal Health Services', 'Health Care'],
  ['DVA', 'DaVita', 'Health Care'],
  ['LH', 'Labcorp Holdings', 'Health Care'],
  ['DGX', 'Quest Diagnostics', 'Health Care'],
  ['CRL', 'Charles River Labs', 'Health Care'],
  ['INCY', 'Incyte', 'Health Care'],
  ['EXAS', 'Exact Sciences', 'Health Care'],
  ['NBIX', 'Neurocrine Biosciences', 'Health Care'],
  ['ALNY', 'Alnylam Pharmaceuticals', 'Health Care'],
  ['SRPT', 'Sarepta Therapeutics', 'Health Care'],
  ['UTHR', 'United Therapeutics', 'Health Care'],
  ['JAZZ', 'Jazz Pharmaceuticals', 'Health Care'],
  ['HALO', 'Halozyme Therapeutics', 'Health Care'],
  ['MEDP', 'Medpace Holdings', 'Health Care'],
  ['TECH', 'Bio-Techne', 'Health Care'],
  ['RVTY', 'Revvity', 'Health Care'],
  ['SOLV', 'Solventum', 'Health Care'],
  ['GEHC', 'GE HealthCare', 'Health Care'],
  ['TFX', 'Teleflex', 'Health Care'],
  ['BRKR', 'Bruker', 'Health Care'],
  ['PEN', 'Penumbra', 'Health Care'],
  ['MASI', 'Masimo', 'Health Care'],
  ['BIO', 'Bio-Rad Laboratories', 'Health Care'],

  // ── Financials ────────────────────────────────────────────────────
  ['BRK.B', 'Berkshire Hathaway B', 'Financials'],
  ['JPM', 'JPMorgan Chase', 'Financials'],
  ['V', 'Visa', 'Financials'],
  ['MA', 'Mastercard', 'Financials'],
  ['BAC', 'Bank of America', 'Financials'],
  ['WFC', 'Wells Fargo', 'Financials'],
  ['GS', 'Goldman Sachs', 'Financials'],
  ['MS', 'Morgan Stanley', 'Financials'],
  ['SPGI', 'S&P Global', 'Financials'],
  ['BLK', 'BlackRock', 'Financials'],
  ['AXP', 'American Express', 'Financials'],
  ['C', 'Citigroup', 'Financials'],
  ['SCHW', 'Charles Schwab', 'Financials'],
  ['CB', 'Chubb', 'Financials'],
  ['PGR', 'Progressive', 'Financials'],
  ['MMC', 'Marsh & McLennan', 'Financials'],
  ['ICE', 'Intercontinental Exchange', 'Financials'],
  ['CME', 'CME Group', 'Financials'],
  ['AON', 'Aon', 'Financials'],
  ['PNC', 'PNC Financial Services', 'Financials'],
  ['USB', 'U.S. Bancorp', 'Financials'],
  ['TFC', 'Truist Financial', 'Financials'],
  ['COF', 'Capital One Financial', 'Financials'],
  ['BK', 'Bank of New York Mellon', 'Financials'],
  ['AIG', 'American International Group', 'Financials'],
  ['MET', 'MetLife', 'Financials'],
  ['PRU', 'Prudential Financial', 'Financials'],
  ['TRV', 'Travelers Companies', 'Financials'],
  ['ALL', 'Allstate', 'Financials'],
  ['AFL', 'Aflac', 'Financials'],
  ['AMP', 'Ameriprise Financial', 'Financials'],
  ['DFS', 'Discover Financial', 'Financials'],
  ['SYF', 'Synchrony Financial', 'Financials'],
  ['FITB', 'Fifth Third Bancorp', 'Financials'],
  ['HBAN', 'Huntington Bancshares', 'Financials'],
  ['RF', 'Regions Financial', 'Financials'],
  ['KEY', 'KeyCorp', 'Financials'],
  ['CFG', 'Citizens Financial Group', 'Financials'],
  ['MTB', 'M&T Bank', 'Financials'],
  ['ZION', 'Zions Bancorporation', 'Financials'],
  ['CMA', 'Comerica', 'Financials'],
  ['NTRS', 'Northern Trust', 'Financials'],
  ['STT', 'State Street', 'Financials'],
  ['MSCI', 'MSCI Inc.', 'Financials'],
  ['MCO', "Moody's", 'Financials'],
  ['NDAQ', 'Nasdaq Inc.', 'Financials'],
  ['CBOE', 'Cboe Global Markets', 'Financials'],
  ['FIS', 'Fidelity National Info', 'Financials'],
  ['FI', 'Fiserv', 'Financials'],
  ['GPN', 'Global Payments', 'Financials'],
  ['PYPL', 'PayPal Holdings', 'Financials'],
  ['HOOD', 'Robinhood Markets', 'Financials'],
  ['COIN', 'Coinbase Global', 'Financials'],
  ['SOFI', 'SoFi Technologies', 'Financials'],
  ['ALLY', 'Ally Financial', 'Financials'],
  ['WRB', 'W. R. Berkley', 'Financials'],
  ['CINF', 'Cincinnati Financial', 'Financials'],
  ['L', 'Loews', 'Financials'],
  ['HIG', 'Hartford Insurance Group', 'Financials'],
  ['GL', 'Globe Life', 'Financials'],
  ['ERIE', 'Erie Indemnity', 'Financials'],
  ['BRO', 'Brown & Brown', 'Financials'],
  ['AJG', 'Arthur J. Gallagher', 'Financials'],
  ['RJF', 'Raymond James Financial', 'Financials'],
  ['TROW', 'T. Rowe Price', 'Financials'],
  ['BEN', 'Franklin Resources', 'Financials'],
  ['IVZ', 'Invesco', 'Financials'],
  ['KKR', 'KKR & Co.', 'Financials'],
  ['BX', 'Blackstone', 'Financials'],
  ['APO', 'Apollo Global Management', 'Financials'],
  ['ARES', 'Ares Management', 'Financials'],
  ['CG', 'Carlyle Group', 'Financials'],
  ['TPG', 'TPG Inc.', 'Financials'],
  ['NU', 'Nu Holdings', 'Financials'],

  // ── Industrials ───────────────────────────────────────────────────
  ['GE', 'GE Aerospace', 'Industrials'],
  ['CAT', 'Caterpillar', 'Industrials'],
  ['RTX', 'RTX Corporation', 'Industrials'],
  ['HON', 'Honeywell International', 'Industrials'],
  ['UNP', 'Union Pacific', 'Industrials'],
  ['BA', 'Boeing', 'Industrials'],
  ['LMT', 'Lockheed Martin', 'Industrials'],
  ['DE', 'Deere & Company', 'Industrials'],
  ['UPS', 'United Parcel Service', 'Industrials'],
  ['ETN', 'Eaton Corporation', 'Industrials'],
  ['ADP', 'Automatic Data Processing', 'Industrials'],
  ['GD', 'General Dynamics', 'Industrials'],
  ['NOC', 'Northrop Grumman', 'Industrials'],
  ['CSX', 'CSX Corporation', 'Industrials'],
  ['NSC', 'Norfolk Southern', 'Industrials'],
  ['ITW', 'Illinois Tool Works', 'Industrials'],
  ['EMR', 'Emerson Electric', 'Industrials'],
  ['PH', 'Parker-Hannifin', 'Industrials'],
  ['TT', 'Trane Technologies', 'Industrials'],
  ['CMI', 'Cummins', 'Industrials'],
  ['PCAR', 'PACCAR', 'Industrials'],
  ['JCI', 'Johnson Controls', 'Industrials'],
  ['CARR', 'Carrier Global', 'Industrials'],
  ['OTIS', 'Otis Worldwide', 'Industrials'],
  ['FDX', 'FedEx', 'Industrials'],
  ['WM', 'Waste Management', 'Industrials'],
  ['RSG', 'Republic Services', 'Industrials'],
  ['PAYX', 'Paychex', 'Industrials'],
  ['VRSK', 'Verisk Analytics', 'Industrials'],
  ['CTAS', 'Cintas', 'Industrials'],
  ['FAST', 'Fastenal', 'Industrials'],
  ['GWW', 'W.W. Grainger', 'Industrials'],
  ['URI', 'United Rentals', 'Industrials'],
  ['LHX', 'L3Harris Technologies', 'Industrials'],
  ['TDG', 'TransDigm Group', 'Industrials'],
  ['HWM', 'Howmet Aerospace', 'Industrials'],
  ['AME', 'AMETEK', 'Industrials'],
  ['ROK', 'Rockwell Automation', 'Industrials'],
  ['DOV', 'Dover Corporation', 'Industrials'],
  ['IR', 'Ingersoll Rand', 'Industrials'],
  ['XYL', 'Xylem', 'Industrials'],
  ['PNR', 'Pentair', 'Industrials'],
  ['SWK', 'Stanley Black & Decker', 'Industrials'],
  ['MAS', 'Masco', 'Industrials'],
  ['AOS', 'A. O. Smith', 'Industrials'],
  ['ALLE', 'Allegion', 'Industrials'],
  ['JBHT', 'J.B. Hunt Transport', 'Industrials'],
  ['ODFL', 'Old Dominion Freight', 'Industrials'],
  ['CHRW', 'C.H. Robinson', 'Industrials'],
  ['EXPD', 'Expeditors International', 'Industrials'],
  ['LUV', 'Southwest Airlines', 'Industrials'],
  ['DAL', 'Delta Air Lines', 'Industrials'],
  ['UAL', 'United Airlines', 'Industrials'],
  ['AAL', 'American Airlines', 'Industrials'],
  ['ALK', 'Alaska Air Group', 'Industrials'],
  ['TXT', 'Textron', 'Industrials'],
  ['HII', 'Huntington Ingalls', 'Industrials'],
  ['LDOS', 'Leidos Holdings', 'Industrials'],
  ['BAH', 'Booz Allen Hamilton', 'Industrials'],
  ['CACI', 'CACI International', 'Industrials'],
  ['SAIC', 'Science Applications Intl.', 'Industrials'],
  ['AXON', 'Axon Enterprise', 'Industrials'],
  ['AVAV', 'AeroVironment', 'Industrials'],
  ['GNRC', 'Generac Holdings', 'Industrials'],
  ['NDSN', 'Nordson', 'Industrials'],
  ['GGG', 'Graco', 'Industrials'],
  ['LII', 'Lennox International', 'Industrials'],
  ['BLDR', 'Builders FirstSource', 'Industrials'],
  ['PWR', 'Quanta Services', 'Industrials'],
  ['EME', 'EMCOR Group', 'Industrials'],
  ['J', 'Jacobs Solutions', 'Industrials'],
  ['ACM', 'AECOM', 'Industrials'],
  ['UBER', 'Uber Technologies', 'Industrials'],
  ['FTV', 'Fortive', 'Industrials'],
  ['WAB', 'Westinghouse Air Brake', 'Industrials'],
  ['SNA', 'Snap-on', 'Industrials'],
  ['IEX', 'IDEX Corporation', 'Industrials'],
  ['ROL', 'Rollins', 'Industrials'],

  // ── Energy ────────────────────────────────────────────────────────
  ['XOM', 'Exxon Mobil', 'Energy'],
  ['CVX', 'Chevron', 'Energy'],
  ['COP', 'ConocoPhillips', 'Energy'],
  ['EOG', 'EOG Resources', 'Energy'],
  ['SLB', 'SLB', 'Energy'],
  ['MPC', 'Marathon Petroleum', 'Energy'],
  ['PSX', 'Phillips 66', 'Energy'],
  ['VLO', 'Valero Energy', 'Energy'],
  ['OXY', 'Occidental Petroleum', 'Energy'],
  ['WMB', 'Williams Companies', 'Energy'],
  ['KMI', 'Kinder Morgan', 'Energy'],
  ['OKE', 'ONEOK', 'Energy'],
  ['HES', 'Hess Corporation', 'Energy'],
  ['DVN', 'Devon Energy', 'Energy'],
  ['FANG', 'Diamondback Energy', 'Energy'],
  ['HAL', 'Halliburton', 'Energy'],
  ['BKR', 'Baker Hughes', 'Energy'],
  ['TRGP', 'Targa Resources', 'Energy'],
  ['EQT', 'EQT Corporation', 'Energy'],
  ['CTRA', 'Coterra Energy', 'Energy'],
  ['APA', 'APA Corporation', 'Energy'],
  ['OVV', 'Ovintiv', 'Energy'],
  ['AR', 'Antero Resources', 'Energy'],
  ['RRC', 'Range Resources', 'Energy'],
  ['EXE', 'Expand Energy', 'Energy'],
  ['CHRD', 'Chord Energy', 'Energy'],
  ['PR', 'Permian Resources', 'Energy'],
  ['NOV', 'NOV Inc.', 'Energy'],
  ['FTI', 'TechnipFMC', 'Energy'],
  ['LNG', 'Cheniere Energy', 'Energy'],
  ['MTDR', 'Matador Resources', 'Energy'],

  // ── Utilities ─────────────────────────────────────────────────────
  ['NEE', 'NextEra Energy', 'Utilities'],
  ['SO', 'Southern Company', 'Utilities'],
  ['DUK', 'Duke Energy', 'Utilities'],
  ['CEG', 'Constellation Energy', 'Utilities'],
  ['AEP', 'American Electric Power', 'Utilities'],
  ['SRE', 'Sempra', 'Utilities'],
  ['D', 'Dominion Energy', 'Utilities'],
  ['EXC', 'Exelon', 'Utilities'],
  ['XEL', 'Xcel Energy', 'Utilities'],
  ['PEG', 'Public Service Enterprise', 'Utilities'],
  ['ED', 'Consolidated Edison', 'Utilities'],
  ['WEC', 'WEC Energy Group', 'Utilities'],
  ['ES', 'Eversource Energy', 'Utilities'],
  ['AWK', 'American Water Works', 'Utilities'],
  ['DTE', 'DTE Energy', 'Utilities'],
  ['PPL', 'PPL Corporation', 'Utilities'],
  ['AEE', 'Ameren', 'Utilities'],
  ['CMS', 'CMS Energy', 'Utilities'],
  ['FE', 'FirstEnergy', 'Utilities'],
  ['ATO', 'Atmos Energy', 'Utilities'],
  ['CNP', 'CenterPoint Energy', 'Utilities'],
  ['NI', 'NiSource', 'Utilities'],
  ['LNT', 'Alliant Energy', 'Utilities'],
  ['EVRG', 'Evergy', 'Utilities'],
  ['PNW', 'Pinnacle West Capital', 'Utilities'],
  ['NRG', 'NRG Energy', 'Utilities'],
  ['VST', 'Vistra', 'Utilities'],
  ['AES', 'AES Corporation', 'Utilities'],
  ['ETR', 'Entergy', 'Utilities'],
  ['PCG', 'PG&E Corporation', 'Utilities'],

  // ── Real Estate ───────────────────────────────────────────────────
  ['PLD', 'Prologis', 'Real Estate'],
  ['AMT', 'American Tower', 'Real Estate'],
  ['EQIX', 'Equinix', 'Real Estate'],
  ['WELL', 'Welltower', 'Real Estate'],
  ['SPG', 'Simon Property Group', 'Real Estate'],
  ['PSA', 'Public Storage', 'Real Estate'],
  ['O', 'Realty Income', 'Real Estate'],
  ['CCI', 'Crown Castle', 'Real Estate'],
  ['DLR', 'Digital Realty Trust', 'Real Estate'],
  ['EXR', 'Extra Space Storage', 'Real Estate'],
  ['AVB', 'AvalonBay Communities', 'Real Estate'],
  ['EQR', 'Equity Residential', 'Real Estate'],
  ['VICI', 'VICI Properties', 'Real Estate'],
  ['IRM', 'Iron Mountain', 'Real Estate'],
  ['SBAC', 'SBA Communications', 'Real Estate'],
  ['MAA', 'Mid-America Apartment', 'Real Estate'],
  ['ESS', 'Essex Property Trust', 'Real Estate'],
  ['UDR', 'UDR Inc.', 'Real Estate'],
  ['INVH', 'Invitation Homes', 'Real Estate'],
  ['AMH', 'American Homes 4 Rent', 'Real Estate'],
  ['ARE', 'Alexandria Real Estate', 'Real Estate'],
  ['BXP', 'BXP Inc.', 'Real Estate'],
  ['VTR', 'Ventas', 'Real Estate'],
  ['DOC', 'Healthpeak Properties', 'Real Estate'],
  ['KIM', 'Kimco Realty', 'Real Estate'],
  ['REG', 'Regency Centers', 'Real Estate'],
  ['FRT', 'Federal Realty', 'Real Estate'],
  ['CPT', 'Camden Property Trust', 'Real Estate'],
  ['HST', 'Host Hotels & Resorts', 'Real Estate'],
  ['WY', 'Weyerhaeuser', 'Real Estate'],
  ['CBRE', 'CBRE Group', 'Real Estate'],

  // ── Materials ─────────────────────────────────────────────────────
  ['LIN', 'Linde', 'Materials'],
  ['SHW', 'Sherwin-Williams', 'Materials'],
  ['APD', 'Air Products & Chemicals', 'Materials'],
  ['ECL', 'Ecolab', 'Materials'],
  ['FCX', 'Freeport-McMoRan', 'Materials'],
  ['NEM', 'Newmont', 'Materials'],
  ['NUE', 'Nucor', 'Materials'],
  ['DOW', 'Dow Inc.', 'Materials'],
  ['DD', 'DuPont de Nemours', 'Materials'],
  ['PPG', 'PPG Industries', 'Materials'],
  ['LYB', 'LyondellBasell', 'Materials'],
  ['VMC', 'Vulcan Materials', 'Materials'],
  ['MLM', 'Martin Marietta Materials', 'Materials'],
  ['STLD', 'Steel Dynamics', 'Materials'],
  ['CLF', 'Cleveland-Cliffs', 'Materials'],
  ['ALB', 'Albemarle', 'Materials'],
  ['CE', 'Celanese', 'Materials'],
  ['EMN', 'Eastman Chemical', 'Materials'],
  ['MOS', 'Mosaic', 'Materials'],
  ['CF', 'CF Industries', 'Materials'],
  ['FMC', 'FMC Corporation', 'Materials'],
  ['IFF', 'International Flavors', 'Materials'],
  ['AVY', 'Avery Dennison', 'Materials'],
  ['PKG', 'Packaging Corp of America', 'Materials'],
  ['IP', 'International Paper', 'Materials'],
  ['AMCR', 'Amcor', 'Materials'],
  ['SMG', 'Scotts Miracle-Gro', 'Materials'],
  ['RPM', 'RPM International', 'Materials'],
  ['AXTA', 'Axalta Coating Systems', 'Materials'],
  ['RS', 'Reliance Inc.', 'Materials'],
];

/* Derived lookups, built once. */
const UNIVERSE_NAMES = new Map(UNIVERSE.map(([symbol, name]) => [symbol, name]));
const UNIVERSE_SECTORS = new Map(UNIVERSE.map(([symbol, , sector]) => [symbol, sector]));
const SECTOR_LIST = [...new Set(UNIVERSE.map(([, , sector]) => sector))].sort();
